title:            Ben Dechant's site
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //Benjamin-Dechant.github.io
#http://localhost:5000
#https://Benjamin-Dechant.github.io
disqus_shortname: BenDechant

# Owner/author information
owner:
  name:           Benjamin Dechant
  avatar:         jordi.png
  bio:            I'm from Bavaria, Germany. Currently living in Leipzig, Germany. 
  email:          benjamin.dechant@idiv.de
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: DechantBenjamin
  google_scholar: aGCI-yQAAAAJ&hl
  orcid: 0000-0001-5171-2364
  publons: 1313475
  #github: jponttuset
# Analytics and webmaster tools stuff goes here
#google_analytics: UA-52736040-1
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: CV
    url: /cv/
  - title: Publications
    url: /publications/
  #- title: Code
   # url: /code/
  #- title: Blog
  #  url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

theme: jekyll-theme-minimal
